### ISSUE TITLE
Why are numeric paramaters in SearchParameters types as strings ?

### ISSUE THREAD

**Issue by PhenX** [DAXGRID/typesense-dotnet#122]
They are numbers in official clients like https://github.com/typesense/typesense-js/blob/master/src/Typesense/Documents.ts

It would far easier to use with numeric types

**Comment by runeanielsen** [comment]
Hi @PhenX,
Hello @PhenX,

I'm unclear on the reasoning behind a previous decision that was made. Could you provide a list of the fields that need to be modified, along with their desired new values? It would also be a good idea to check other types to ensure that they align with the documentation, so that we can make all necessary changes at once, since it will result in a major release because of breaking API changes.

**Comment by PhenX** [comment]
I didn't see any other properties that required a different type than theses ones, all numeric :
 
 * page
 * per_page
 * max_facet_values
 * facet_query_num_typos (already int)
 * group_limit
 * highlight_affix_num_tokens
 * snippet_threshold
 * limit_hits
 * search_cutoff_ms (not present, but in my other PR)
 * max_candidates (already int)
 * num_typos
 * min_len_1typo (not present, but in my other PR)
 * min_len_2typo (not present, but in my other PR)
 * typo_tokens_threshold
 * drop_tokens_threshold
 * cache_ttl (not present, but in my other PR)

As of the numeric type, I think an int should be good

**Comment by runeanielsen** [comment]
Sounds good, I'll do the change after we have handled the other PR's. :+1:
